### ISSUE TITLE
Every x minutes scheduling problem

### ISSUE THREAD

**Issue by Jackyjjc** [bunkat/later#109]
I schedule a task to run every 40 minutes:

```
{
      type: 'text',
      cron: 'every 40 minutes',
      exec: 'backup'
}
```

And it ran at:

```
August 5th 2015, 20:00:00.000		Starting job
August 5th 2015, 19:40:00.000		Starting job
August 5th 2015, 19:00:00.000		Starting job
August 5th 2015, 18:40:00.000		Starting job
```

18:40 and 19:00 is only 20 minutes apart?

**Comment by Jackyjjc** [comment]
we use later.setInterval(job, later.parse('every 40 minutes')) to schedule the jobs

**Comment by bunkat** [comment]
This is a common misunderstanding with Later. Later is for defining deterministic schedules only, that is, schedules that produce the same valid occurrences no matter when the schedule is executed or what start date is used. A schedule such as every 40 minutes starting from x is not deterministic because the results will change depending on what x is used.

Instead, when you request a schedule that occurs `every 40 minutes` you are telling Later that minutes 0 and minutes 40 should be considered valid. And this is the result that was returned. You can do `console.log(later.parse.text('every 40 minutes')` to view the set of constraints that Later will use to find valid schedules.

**Comment by Jackyjjc** [comment]
so what should I do if I want to run it every 40 minutes?

**Comment by bunkat** [comment]
If you really just need every 40 minutes, then you probably don't need to use Laterjs.  You should just use Cron directly.
