### ISSUE TITLE
Using setInterval and schedule.next has a race condition when used together

### ISSUE THREAD

**Issue by AlaRuba** [bunkat/later#118]
Hi,

I'm not sure if race condition is the right way to describe this.

So I was playing around with cron strings that executed every couple of minutes like '*/2 * * * *'.

Now, I used setInterval to run some jobs with the same cronString like so

```
later.setInterval(function() {
    Queue.add({job: jobCode, cron: cronString});
}, s);
```

and then when the job is processed, I want to save when I ran it and when I should run it next based off the schedule. The reason I do this is case my program shuts down, it can start up and run any tasks it missed. So when I pull from the queue, I do the job, and then save the next stuff in the database. 

Given that I passed the cronString, I figured I could generate the next time I should run it. However, I run into a race condition, where for example, if the time of execution is 2015-09-16T01:14:00.863Z,
and I get the next time to run when the job is simple like console.log, I get 2015-09-16T01:14:00.864Z, instead of 2015-09-16T01:16:00.864Z, if my rule were every 2 minutes.

Here is how I generate the next time to run.

```
var cronString = job.data.cron;
var s = later.parse.cron(cronString);
var nextRun = later.schedule(s).next(1);
nextRun = nextRun.toISOString();
```

Any suggestion on how to remove this race condition?

**Comment by bunkat** [comment]
This is by design. It's good to keep in mind that Later is not 'smart', it doesn't know what the current date is or what a date even is.  It just knows how to check a value against a set of constraints. So if the current time meets all of the constraints of the schedule it will be returned as a valid result.

In this case, you can prevent the race condition by asking for the next two start times and throwing out the first one if it is the same as the start time.

Warning: untested code follows:

````
var startAt = new Date();
var cronString = job.data.cron;
var s = later.parse.cron(cronString);
var nextRun = later.schedule(s).nextRange(2, startAt);
nextRun = nextRun[0].getTime() === startAt.getTime() ? nextRun[1] : nextRun[0];
````
