### ISSUE TITLE
Wrong amount of occurencies

### ISSUE THREAD

**Issue by Olmer1st** [bunkat/later#159]
Hi,
Found an interesting problem when the day already pass
later.date.localTime();
var parser = later.parse.text("at 03:39pm on the 22th day of April in 2016");
var scheduler = later.schedule(parser);
var occurrences = scheduler.next(10);
console.log("next runs: ", occurrences);

Result:
next runs:  [ Sun Apr 24 2016 15:39:00 GMT+0300 (IDT),
  Mon Apr 25 2016 15:39:00 GMT+0300 (IDT),
  Tue Apr 26 2016 15:39:00 GMT+0300 (IDT),
  Wed Apr 27 2016 15:39:00 GMT+0300 (IDT),
  Thu Apr 28 2016 15:39:00 GMT+0300 (IDT),
  Fri Apr 29 2016 15:39:00 GMT+0300 (IDT),
  Sat Apr 30 2016 15:39:00 GMT+0300 (IDT),
  Sun May 01 2016 15:39:00 GMT+0300 (IDT),
  Mon May 02 2016 15:39:00 GMT+0300 (IDT),
  Tue May 03 2016 15:39:00 GMT+0300 (IDT) ]

later.date.localTime();
var parser = later.parse.text("at 03:39pm on the 24th day of April in 2016");
var scheduler = later.schedule(parser);
var occurrences = scheduler.next(10);
console.log("next runs: ", occurrences);

Result:
next runs:  [ Sun Apr 24 2016 15:39:00 GMT+0300 (IDT) ]

I think it's a bug in 1st example, because in this case it work correct:
**(the time already pass but the day no)**
later.date.localTime();
var parser = later.parse.text("at 02:39pm on the 24th day of April in 2016");
var scheduler = later.schedule(parser);
var occurrences = scheduler.next(10);
console.log("next runs: ", occurrences);

Result:
next runs:  0

**Comment by Olmer1st** [comment]
Hi,

Any idea?

**Comment by Olmer1st** [comment]
Hi,

Any idea? Or this project not in maintenance anymore?

**Comment by bunkat** [comment]
Sorry I haven't been very responsive, I have a new baby at home that has been eating most of my time.  Looks like there is a parse error in your first example.  If you console.log(parser) you'll see that it encountered an error on character 18.  

Looks like the problem is that it should be 22nd and not 22th.  If you are a non-native user, you can always just specify 22 as well.  That should fix your problem.  

Apologies again that I didn't answer this sooner.

**Comment by Olmer1st** [comment]
@bunkat Congratulations for new baby!!! :-)

Thank you for help, it's work.
