### ISSUE TITLE
Seconds/ minutes not functioning as expected

### ISSUE THREAD

**Issue by Daniel-Goodwin** [bunkat/later#183]
Every 60 seconds doesn't work and silently errors, same with every 60 minutes - however every 61 seconds does work.

**Comment by bunkat** [comment]
Later doesn't work the way you think it does.  It's a constraint based system where you specify the constraints a time must meet in order to be considered valid.  A constraint of 'every 1 second' means that any time where the seconds value is 1 will be considered valid - it does not mean return the next value every 1 second.  Since no minute or hour every has a seconds value of 60, no times will ever be considered valid.
