### ISSUE TITLE
Day of week issue

### ISSUE THREAD

**Issue by deadbeef84** [bunkat/later#191]
There seems to be a bug when specifying multiple days of week:
```js
> const s = later.parse.text('at 15:50 on Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday')
{ schedules: [ { t: [ 57000 ], d: [ 2, 3, 4, 5, 6, 7, 1 ] },
  exceptions: [],
  error: -1 ]
> later.schedule(s).next(5)
[ '2016-11-28T15:50:00.000Z',
  '2016-12-05T15:50:00.000Z',
  '2016-12-12T15:50:00.000Z',
  '2016-12-19T15:50:00.000Z',
  '2016-12-26T15:50:00.000Z ]'
```
According to the [documentation](http://bunkat.github.io/later/parsers.html#text) I would expect this to generate one entry for every day, however it seem to only include mondays. Have I misunderstood anything? Is there any way I can make it work the way I expect it to?

**Comment by bunkat** [comment]
The problem is that the day array (d) needs to be sorted before calculating schedules.  The text parser should do this for you but it currently doesn't so you would need to start the constraint with Sunday. If you want something everyday, you can just leave out the day constraint all together (no constraint just means that any value is valid).  So "at 15:50" is equivalent in this case.

**Comment by deadbeef84** [comment]
Alright, that makes sense. Extra confusing for us that live in the part of the world where Monday is the first day of the week. Yes I understand that including all days was a bit silly, but it demonstrated the problem nicely :)
