### ISSUE TITLE
If number larger 60?

### ISSUE THREAD

**Issue by mynoheart** [bunkat/later#85]
how do schedule every 90 minutes?
```javascript
later.parse('every 90 min') //{ schedules: [], exceptions: [], error: 6 }
later.parse('every 59 min') //ok
later.parse('every 60 min') //{ schedules: [], exceptions: [], error: 6 }
```

**Comment by iskuhar** [comment]
For later.js "every 90 min" means "every 90th minute [of the hour]", which
doesn't make sense.

You don't need later.js to do something "every 90 min".

Just use:
.setInterval(function(){}, 5400000);

Cheers,
Igor

**Comment by mynoheart** [comment]
thanks, but 25 hours works correctly.
```javascript
later.parse('every 25 hours') //ok
```

**Comment by bunkat** [comment]
Later parses any hours > 24 as `the 0th hour` of every day.  You can see this by doing `console.log(s)` and looking at s.schedules[0].h, this will indicate which hours are considered valid.  @iskuhar is correct that there is no way to say `every 90 mins from now` because Later has no memory, it has no notion of schedules that have happened earlier.  You can only say things like `on the 30th minute of the hour` (and much more complicated things).

You could definitely encode `every 90 minutes` in a bunch of different ways but if you just want `every 90 minutes from now` then Later is not a good fit for you.

**Comment by mynoheart** [comment]
Thanks for your answers.
