### ISSUE TITLE
MomentJS

### ISSUE THREAD

**Issue by ilanbiala** [bunkat/later#86]
http://momentjs.com/docs/#/plugins/recur/ seems pretty similar to some functionality here. Does it make sense to use that instead or combine some of the functionality into that plugin?

**Comment by bunkat** [comment]
I'm not sure what your question is.  If you want to use MomentJS, then that is up to you.  If you are asking if I'm going to try and port the functionality of Later into MomentJS, then no I'm not. Later provides significantly more functionality than the recur plugin that you linked to.

**Comment by ilanbiala** [comment]
@bunkat what I'm saying is why not use Moment instead of having code in Later that is probably better handled there?

**Comment by bunkat** [comment]
The date functions in Later are significantly smaller and significantly faster than MomentJS since they have been optimized for producing schedule occurrences.  Seems silly to take a dependency on a library that is twice as large (34kb vs 16kb), slower, and which I have no control over just for some vague notion that the code is 'probably better handled there'.
